name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    uses: roschaefer/reusable-workflows/.github/workflows/rust-ci.yml@1155bd6b30f7365cdfcfdbe628c9d014d49a2b26 # main
    permissions:
      contents: write
    with:
      binary_name: hledger-elster
      platforms: '["linux-x86_64","macos-arm64"]'
      needs_hledger: true
